# Generated by Django 6.0.1 on 2026-01-20 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата')),
                ('index_views', models.PositiveIntegerField(default=0, verbose_name='Просмотры главной')),
                ('process_requests', models.PositiveIntegerField(default=0, verbose_name='Запросы на обработку')),
                ('chars_in', models.BigIntegerField(default=0, verbose_name='Символов на входе')),
                ('chars_out', models.BigIntegerField(default=0, verbose_name='Символов на выходе')),
                ('total_processing_time_ms', models.FloatField(default=0.0, verbose_name='Суммарное время обработки (мс)')),
                ('settings_stats', models.JSONField(default=dict, verbose_name='Статистика настроек')),
            ],
            options={
                'verbose_name': 'Дневная статистика',
                'verbose_name_plural': 'Дневная статистика',
                'ordering': ['-date'],
            },
        ),
    ]
