# Generated by Django 6.0.1 on 2026-01-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typograph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystat',
            name='copy_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Копирований в буфер'),
        ),
    ]
