# Generated by Django 6.0.1 on 2026-01-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typograph', '0002_dailystat_copy_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystat',
            name='chars_copied',
            field=models.BigIntegerField(default=0, verbose_name='Символов скопировано'),
        ),
    ]
