# Generated by Django 6.0.1 on 2026-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении.', verbose_name='Дата обновления'),
        ),
    ]
